import type { Metadata } from "next";
import { Ovo } from 'next/font/google';
import "./globals.css";

 const ovo = Ovo({
  subsets:["latin"],
  weight: ["400"]
 })

export const metadata: Metadata = {
  title: "Portfolio - Tanvir Rubayed",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${ovo.className} scroll-smooth`}>
      <body className="leading-8 overfloew-x-hidden">
        {children}
      </body>
    </html>
  );
}
